services:
  db-renfe:
    image: danidrq89/renfe:latest
    container_name: db-renfe
    ports:
      - "3306:3306"
    networks:
      - renfe-network
    restart: always

  api-renfe:
    image: danidrq89/renfe-api:latest
    container_name: api-renfe
    ports:
      - "8081:8080"
    networks:
      - renfe-network
    depends_on:
      - db-renfe
    restart: on-failure

networks:
  renfe-network:
    driver: bridge